import json
import os

notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {"id": "markdown-1"},
   "source": [
    "# GenCast Podcast Generation\n",
    "This notebook replicates the podcast generation flow from the GenCast project.\n",
    "It covers Plan Generation (with Google Search Grounding), Script Generation, and Edge TTS Audio Synthesis."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {"id": "setup-1"},
   "outputs": [],
   "source": [
    "!pip install google-genai edge-tts"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {"id": "imports-1"},
   "outputs": [],
   "source": [
    "import json\n",
    "import re\n",
    "import asyncio\n",
    "import io\n",
    "from google import genai\n",
    "from google.genai import types\n",
    "import edge_tts\n",
    "from IPython.display import display, Audio\n",
    "\n",
    "# In Colab, we use userdata for secrets\n",
    "try:\n",
    "    from google.colab import userdata\n",
    "    GEMINI_API_KEY = userdata.get('GEMINI_API_KEY')\n",
    "except Exception:\n",
    "    # Fallback or prompt\n",
    "    print(\"Please set GEMINI_API_KEY in Colab Secrets (userdata).\")\n",
    "    GEMINI_API_KEY = \"\" # Add key here if not using colab userdata\n",
    "\n",
    "if GEMINI_API_KEY:\n",
    "    client = genai.Client(api_key=GEMINI_API_KEY)\n",
    "else:\n",
    "    print(\"WARNING: No Gemini API Key provided.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {"id": "functions-1"},
   "outputs": [],
   "source": [
    "# Helper Functions\n",
    "def generate_plan(topic, speaker_count=2):\n",
    "    search_prompt = f\"\"\"\n",
    "    You are an expert researcher.\n",
    "    Topic: \\\"{topic}\\\"\n",
    "    \n",
    "    Your task is to thoroughly research this topic using Google Search.\n",
    "    Gather factual, relevant, and up-to-date information, focusing on key points \n",
    "    that would make for an engaging {speaker_count}-speaker podcast episode.\n",
    "    Write a detailed summary of your findings to be used for planning the episode.\n",
    "    \"\"\"\n",
    "    \n",
    "    search_response = client.models.generate_content(\n",
    "        model='gemini-2.5-flash',\n",
    "        contents=search_prompt,\n",
    "        config=types.GenerateContentConfig(\n",
    "            tools=[{\"google_search\": {}}]\n",
    "        )\n",
    "    )\n",
    "    \n",
    "    research_text = search_response.text or \"\"\n",
    "    \n",
    "    sources = []\n",
    "    if search_response.candidates:\n",
    "        grounding = search_response.candidates[0].grounding_metadata\n",
    "        if grounding and getattr(grounding, 'grounding_chunks', None):\n",
    "            for chunk in grounding.grounding_chunks:\n",
    "                if getattr(chunk, 'web', None) and getattr(chunk.web, 'uri', None) and getattr(chunk.web, 'title', None):\n",
    "                    sources.append({\n",
    "                        \"title\": chunk.web.title,\n",
    "                        \"uri\": chunk.web.uri\n",
    "                    })\n",
    "                \n",
    "    unique_sources = []\n",
    "    seen_uris = set()\n",
    "    for s in sources:\n",
    "        if s['uri'] not in seen_uris:\n",
    "            unique_sources.append(s)\n",
    "            seen_uris.add(s['uri'])\n",
    "            \n",
    "    outline_prompt = f\"\"\"\n",
    "    You are an expert podcast producer. \n",
    "    Topic: \\\"{topic}\\\"\n",
    "    Target format: A structured podcast with {speaker_count} speakers.\n",
    "    \n",
    "    Research Material from Preliminary Search:\n",
    "    {research_text}\n",
    "    \n",
    "    Task:\n",
    "    1. Create a high-level outline for a 5-minute podcast episode based on the Research Material above.\n",
    "    2. The outline should include a catchy title, a brief summary, and 4-5 key discussion points (subtopics).\n",
    "    \n",
    "    OUTPUT FORMAT:\n",
    "    Return strictly a JSON object with this structure:\n",
    "    {{\n",
    "      \"title\": \"Episode Title\",\n",
    "      \"summary\": \"Brief summary...\",\n",
    "      \"topics\": [\"Topic 1\", \"Topic 2\", ...]\n",
    "    }}\n",
    "    Do not include any markdown formatting or explanations outside the JSON.\n",
    "    \"\"\"\n",
    "    \n",
    "    outline_response = client.models.generate_content(\n",
    "        model='gemini-2.5-flash',\n",
    "        contents=outline_prompt,\n",
    "        config=types.GenerateContentConfig(\n",
    "            response_mime_type=\"application/json\"\n",
    "        )\n",
    "    )\n",
    "    \n",
    "    text = outline_response.text or \"{}\"\n",
    "    try:\n",
    "        outline = json.loads(text)\n",
    "    except json.JSONDecodeError:\n",
    "        match = re.search(r'(\\{.*\\})', text, re.DOTALL)\n",
    "        if match:\n",
    "            outline = json.loads(match.group(1))\n",
    "        else:\n",
    "            raise ValueError(\"Failed to parse Gemini response as JSON\")\n",
    "            \n",
    "    return {\"outline\": outline, \"sources\": unique_sources}\n",
    "\n",
    "def generate_script(outline, sources, speaker_count=2, speaker_characteristics=None):\n",
    "    sources = sources or []\n",
    "    source_context = \"\\n\".join([f\"- {s['title']}: {s['uri']}\" for s in sources])\n",
    "    \n",
    "    characteristics_context = \"\"\n",
    "    if speaker_characteristics and isinstance(speaker_characteristics, list) and len(speaker_characteristics) > 0:\n",
    "        characteristics_context = \"Speaker Characteristics:\\n\"\n",
    "        for i, char in enumerate(speaker_characteristics):\n",
    "            speaker_label = f\"Speaker {i+1}\"\n",
    "            if i == 0: speaker_label = \"Host\"\n",
    "            elif i == 1: speaker_label = \"Guest\"\n",
    "            characteristics_context += f\"- {speaker_label}: {char}\\n\"\n",
    "        characteristics_context += \"\\nIMPORTANT: Ensure the dialogue reflects each speaker's distinct personality, knowledge level, role, and background as defined above. Their tone and style must match these characteristics exactly.\\n\"\n",
    "    \n",
    "    available_voices_context = \"\"\"\n",
    "    Available Voices for Selection:\n",
    "    - en-US-GuyNeural (Male, Adult)\n",
    "    - en-US-JennyNeural (Female, Adult)\n",
    "    - en-US-AriaNeural (Female, Adult)\n",
    "    - en-US-AnaNeural (Female, Child, young and bright)\n",
    "    - en-US-ChristopherNeural (Male, Adult)\n",
    "    - en-US-EricNeural (Male, Adult, deep or older voice)\n",
    "    - en-US-MichelleNeural (Female, Adult)\n",
    "    - en-US-RogerNeural (Male, Adult)\n",
    "    - en-US-SteffanNeural (Male, Adult)\n",
    "    \"\"\"\n",
    "\n",
    "    prompt = f\"\"\"\n",
    "    You are a professional scriptwriter.\n",
    "    \n",
    "    Podcast Title: {outline.get('title')}\n",
    "    Summary: {outline.get('summary')}\n",
    "    Key Topics: {', '.join(outline.get('topics', []))}\n",
    "    Context/Sources:\n",
    "    {source_context}\n",
    "    \n",
    "    {characteristics_context}\n",
    "    \n",
    "    {available_voices_context}\n",
    "    \n",
    "    Task:\n",
    "    Write a natural, engaging podcast script for {speaker_count} speakers.\n",
    "    The speakers should be labeled strictly as \\\"Host\\\", \\\"Guest\\\", \\\"Speaker 3\\\", etc. to match the given characteristics.\n",
    "    The dialogue should flow naturally, be informative, and follow the provided outline.\n",
    "    Include approximately 10-15 dialogue turns.\n",
    "    \n",
    "    CRITICAL INSTRUCTION FOR VOICE ACTING:\n",
    "    For each line of dialogue, you MUST assign an appropriate `voice` ONLY from the \\\"Available Voices\\\" list above that best matches the speaker's characteristics.\n",
    "    You MUST also optionally specify `pitch` and `rate` to accurately reflect their age and energy level if it deviates from a standard adult. \n",
    "    FORMAT RULES FOR PITCH AND RATE:\n",
    "    - `pitch` MUST be formatted as \\\"+<number>Hz\\\" or \\\"-<number>Hz\\\" (e.g., \\\"+10Hz\\\", \\\"-5Hz\\\"). \n",
    "    - `rate` MUST be formatted as \\\"+<number>%\\\" or \\\"-<number>%\\\" (e.g., \\\"+5%\\\", \\\"-10%\\\").\n",
    "    - If no adjustment is needed, default to \\\"+0Hz\\\" and \\\"+0%\\\".\n",
    "\n",
    "    Return a valid JSON dictionary with a \\\"script\\\" key containing a list of objects.\n",
    "    Example:\n",
    "    {{\n",
    "        \\\"script\\\": [\n",
    "            {{ \\\"speaker\\\": \\\"Host\\\", \\\"voice\\\": \\\"en-US-GuyNeural\\\", \\\"pitch\\\": \\\"+0Hz\\\", \\\"rate\\\": \\\"+0%\\\", \\\"text\\\": \\\"Welcome to the show!\\\" }},\n",
    "            {{ \\\"speaker\\\": \\\"Guest\\\", \\\"voice\\\": \\\"en-US-AnaNeural\\\", \\\"pitch\\\": \\\"+5Hz\\\", \\\"rate\\\": \\\"+10%\\\", \\\"text\\\": \\\"Thanks for having me, I'm super excited!\\\" }}\n",
    "        ]\n",
    "    }}\n",
    "    \"\"\"\n",
    "    \n",
    "    response = client.models.generate_content(\n",
    "        model='gemini-2.5-flash',\n",
    "        contents=prompt,\n",
    "        config=types.GenerateContentConfig(\n",
    "            response_mime_type=\"application/json\"\n",
    "        )\n",
    "    )\n",
    "    \n",
    "    text = response.text or \"{}\"\n",
    "    try:\n",
    "        result = json.loads(text)\n",
    "        if isinstance(result, list):\n",
    "            return result\n",
    "        return result.get(\"script\", [])\n",
    "    except json.JSONDecodeError:\n",
    "        match = re.search(r'(\\{.*\\})', text, re.DOTALL)\n",
    "        if match:\n",
    "            result = json.loads(match.group(1))\n",
    "            if isinstance(result, list):\n",
    "                return result\n",
    "            return result.get(\"script\", [])\n",
    "        else:\n",
    "            raise ValueError(\"Failed to parse generated script as JSON\")\n",
    "\n",
    "async def synthesize_line_edge(text: str, voice: str, pitch: str = \"+0Hz\", rate: str = \"+0%\") -> bytes:\n",
    "    communicate = edge_tts.Communicate(text, voice, pitch=pitch, rate=rate)\n",
    "    mp3_io = io.BytesIO()\n",
    "    async for chunk in communicate.stream():\n",
    "        if chunk[\"type\"] == \"audio\":\n",
    "            mp3_io.write(chunk[\"data\"])\n",
    "    return mp3_io.getvalue()\n",
    "\n",
    "async def synthesize_podcast(script):\n",
    "    segments = []\n",
    "    for line in script:\n",
    "        speaker = line.get('speaker', 'Host')\n",
    "        text = line.get('text', '')\n",
    "        voice = line.get('voice', 'en-US-GuyNeural')\n",
    "        pitch = line.get('pitch', '+0Hz')\n",
    "        rate = line.get('rate', '+0%')\n",
    "        \n",
    "        if not text.strip():\n",
    "            continue\n",
    "            \n",
    "        for _ in range(3):\n",
    "            try:\n",
    "                audio_bytes = await synthesize_line_edge(text, voice, pitch, rate)\n",
    "                segments.append(audio_bytes)\n",
    "                break\n",
    "            except Exception as e:\n",
    "                print(f\"Error synthesizing line: {e}, retrying...\")\n",
    "                await asyncio.sleep(1)\n",
    "                \n",
    "    return segments"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {"id": "execution-1"},
   "outputs": [],
   "source": [
    "# Execution\n",
    "\n",
    "# 1. Define inputs\n",
    "topic = \"The Future of AI Agents in Software Development\"\n",
    "speaker_count = 2\n",
    "speaker_characteristics = [\n",
    "    \"An enthusiastic tech optimist software engineer\",\n",
    "    \"A skeptical but curious security researcher\"\n",
    "]\n",
    "\n",
    "print(f\"Generating plan for topic: '{topic}'...\")\n",
    "\n",
    "# 2. Generate Plan\n",
    "plan_result = generate_plan(topic, speaker_count)\n",
    "outline = plan_result['outline']\n",
    "sources = plan_result['sources']\n",
    "\n",
    "print(f\"\\nOutline Title: {outline.get('title')}\")\n",
    "print(f\"Summary: {outline.get('summary')}\")\n",
    "print(\"\\nSources:\")\n",
    "for s in sources:\n",
    "    print(f\"- {s['title']} ({s['uri']})\")\n",
    "\n",
    "# 3. Generate Script\n",
    "print(\"\\nGenerating script...\")\n",
    "script = generate_script(outline, sources, speaker_count, speaker_characteristics)\n",
    "\n",
    "print(\"\\nScript generated. Lines:\", len(script))\n",
    "for line in script:\n",
    "    print(f\"[{line.get('speaker')}]: {line.get('text')}\")\n",
    "\n",
    "# 4. Generate Audio\n",
    "print(\"\\nSynthesizing audio using Edge TTS...\")\n",
    "# Notebooks already run in an event loop, so we can await directly\n",
    "segments = await synthesize_podcast(script)\n",
    "\n",
    "if segments:\n",
    "    audio_data = b\"\".join(segments)\n",
    "    \n",
    "    # Save to file\n",
    "    with open(\"podcast_output.mp3\", \"wb\") as f:\n",
    "        f.write(audio_data)\n",
    "        \n",
    "    print(\"\\nPodcast audio generated! Listen below:\")\n",
    "    display(Audio(data=audio_data, autoplay=False))\n",
    "else:\n",
    "    print(\"No audio segments were generated.\")"
   ]
  }
 ],
 "metadata": {
  "accelerator": "GPU",
  "colab": {
   "gpuType": "T4",
   "provenance": []
  },
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}

with open(r"d:\dev\GenCast\Local_GenCast.ipynb", "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=1)
print("Notebook generated successfully at d:\\dev\\GenCast\\Local_GenCast.ipynb")
