# Generated by Django 5.2.9 on 2026-02-11 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='audio_file_url',
        ),
        migrations.AddField(
            model_name='podcast',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='podcasts/'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='outline',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='sources',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='speaker_count',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='podcast',
            name='status',
            field=models.CharField(choices=[('planning', 'Planning'), ('planned', 'Planned'), ('scripted', 'Scripted'), ('synthesizing', 'Synthesizing'), ('completed', 'Completed'), ('failed', 'Failed')], default='planning', max_length=20),
        ),
    ]
