# Generated by Django 5.2.9 on 2026-03-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_remove_podcast_audio_file_url_podcast_audio_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='speaker_characteristics',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
