# Generated by Django 5.2.9 on 2026-03-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0003_podcast_speaker_characteristics'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='audio_latency',
            field=models.FloatField(blank=True, help_text='Time taken for audio synthesis in seconds', null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='planning_latency',
            field=models.FloatField(blank=True, help_text='Time taken for planning phase in seconds', null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='scripting_latency',
            field=models.FloatField(blank=True, help_text='Time taken for script generation in seconds', null=True),
        ),
    ]
