# Generated by Django 5.2.9 on 2026-03-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0004_podcast_audio_latency_podcast_planning_latency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='research_context',
            field=models.TextField(blank=True, help_text='Stored RAG context for script generation', null=True),
        ),
    ]
