# Generated by Django 5.2.9 on 2026-04-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0004_podcast_audio_latency_podcast_planning_latency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='language',
            field=models.CharField(default='English', max_length=50),
        ),
    ]
